version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7.3-fpm-alpine
        volumes:
            - .:/usr/share/nginx/html
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.100.20 remote_port=9000 idekey=PHPSTORM"
